import type { AppUser, AppTrip, AppNotification } from './app-types';

export const demoUsers: Record<string, AppUser> = {
  vendorFree: {
    id: 'v003',
    name: 'Mohan Verma',
    phone: '+91 97140 33456',
    email: 'mohan@vermatransport.in',
    role: 'vendor',
    status: 'active',
    isPremium: false,
    city: 'Vadodara',
    companyName: 'Verma Transport',
  },
  vendorPremium: {
    id: 'v001',
    name: 'Rajesh Patel',
    phone: '+91 98250 11234',
    email: 'rajesh@pateltravels.com',
    role: 'vendor',
    status: 'active',
    isPremium: true,
    premiumExpiry: '2025-08-15',
    city: 'Ahmedabad',
    companyName: 'Patel Travels',
  },
  driverFree: {
    id: 'd003',
    name: 'Ramesh Yadav',
    phone: '+91 88660 87654',
    email: 'ramesh.yadav@gmail.com',
    role: 'driver',
    status: 'active',
    isPremium: false,
    city: 'Surat',
    vehicleType: 'Hatchback (Swift)',
  },
  driverPremium: {
    id: 'd001',
    name: 'Harshad Bhatt',
    phone: '+91 98250 65432',
    email: 'harshad@gmail.com',
    role: 'driver',
    status: 'active',
    isPremium: true,
    premiumExpiry: '2025-08-20',
    city: 'Ahmedabad',
    vehicleType: 'Sedan (Toyota Etios)',
  },
};

export const vendorFreeTrips: AppTrip[] = [
  {
    id: 'tr-v003-001',
    vendorId: 'v003',
    vendorName: 'Mohan Verma',
    vendorPhone: '+91 97140 33456',
    fromCity: 'Vadodara',
    toCity: 'Mumbai',
    fromState: 'Gujarat',
    toState: 'Maharashtra',
    vehicleType: 'Truck 14ft',
    loadType: 'General Cargo',
    tripDate: '2025-07-20',
    tripTime: '06:00',
    expectedFare: 18000,
    weightTons: 5,
    notes: 'Morning departure preferred',
    status: 'open',
    isPremiumVendor: false,
    contactsCount: 2,
    contactedDrivers: [],
    createdAt: '2025-07-10T08:00:00Z',
  },
  {
    id: 'tr-v003-002',
    vendorId: 'v003',
    vendorName: 'Mohan Verma',
    vendorPhone: '+91 97140 33456',
    fromCity: 'Vadodara',
    toCity: 'Surat',
    fromState: 'Gujarat',
    toState: 'Gujarat',
    vehicleType: 'Mini Truck',
    loadType: 'FMCG',
    tripDate: '2025-07-18',
    tripTime: '09:00',
    expectedFare: 7000,
    weightTons: 2,
    status: 'closed',
    isPremiumVendor: false,
    contactsCount: 5,
    contactedDrivers: [],
    closureType: 'app_driver',
    closedDriverId: 'd002',
    createdAt: '2025-07-08T10:00:00Z',
  },
  {
    id: 'tr-v003-003',
    vendorId: 'v003',
    vendorName: 'Mohan Verma',
    vendorPhone: '+91 97140 33456',
    fromCity: 'Vadodara',
    toCity: 'Rajkot',
    fromState: 'Gujarat',
    toState: 'Gujarat',
    vehicleType: 'Tempo',
    loadType: 'Electronics',
    tripDate: '2025-07-25',
    tripTime: '08:00',
    expectedFare: 9500,
    weightTons: 1.5,
    status: 'open',
    isPremiumVendor: false,
    contactsCount: 1,
    contactedDrivers: [],
    createdAt: '2025-07-12T09:30:00Z',
  },
  {
    id: 'tr-v003-004',
    vendorId: 'v003',
    vendorName: 'Mohan Verma',
    vendorPhone: '+91 97140 33456',
    fromCity: 'Anand',
    toCity: 'Pune',
    fromState: 'Gujarat',
    toState: 'Maharashtra',
    vehicleType: 'Truck 22ft',
    loadType: 'Machinery',
    tripDate: '2025-07-22',
    tripTime: '05:30',
    expectedFare: 25000,
    weightTons: 10,
    status: 'open',
    isPremiumVendor: false,
    contactsCount: 0,
    contactedDrivers: [],
    createdAt: '2025-07-13T07:00:00Z',
  },
];

export const vendorPremiumTrips: AppTrip[] = [
  {
    id: 'tr-v001-001',
    vendorId: 'v001',
    vendorName: 'Rajesh Patel',
    vendorPhone: '+91 98250 11234',
    fromCity: 'Ahmedabad',
    toCity: 'Delhi',
    fromState: 'Gujarat',
    toState: 'Delhi',
    vehicleType: 'Truck 32ft',
    loadType: 'Auto Parts',
    tripDate: '2025-07-21',
    tripTime: '04:00',
    expectedFare: 55000,
    weightTons: 18,
    notes: 'High-value cargo, need experienced driver',
    status: 'open',
    isPremiumVendor: true,
    contactsCount: 3,
    contactedDrivers: [],
    createdAt: '2025-07-11T06:00:00Z',
  },
  {
    id: 'tr-v001-002',
    vendorId: 'v001',
    vendorName: 'Rajesh Patel',
    vendorPhone: '+91 98250 11234',
    fromCity: 'Ahmedabad',
    toCity: 'Surat',
    fromState: 'Gujarat',
    toState: 'Gujarat',
    vehicleType: 'Mini Truck',
    loadType: 'Textile',
    tripDate: '2025-07-17',
    tripTime: '07:00',
    expectedFare: 8500,
    weightTons: 3,
    status: 'closed',
    isPremiumVendor: true,
    contactsCount: 8,
    contactedDrivers: [],
    closureType: 'app_driver',
    closedDriverId: 'd003',
    createdAt: '2025-07-07T08:00:00Z',
  },
  {
    id: 'tr-v001-003',
    vendorId: 'v001',
    vendorName: 'Rajesh Patel',
    vendorPhone: '+91 98250 11234',
    fromCity: 'Ahmedabad',
    toCity: 'Jaipur',
    fromState: 'Gujarat',
    toState: 'Rajasthan',
    vehicleType: 'Truck 22ft',
    loadType: 'Ceramics',
    tripDate: '2025-07-28',
    tripTime: '05:00',
    expectedFare: 32000,
    weightTons: 12,
    status: 'open',
    isPremiumVendor: true,
    contactsCount: 1,
    contactedDrivers: [],
    createdAt: '2025-07-13T10:00:00Z',
  },
  {
    id: 'tr-v001-004',
    vendorId: 'v001',
    vendorName: 'Rajesh Patel',
    vendorPhone: '+91 98250 11234',
    fromCity: 'Gandhinagar',
    toCity: 'Mumbai',
    fromState: 'Gujarat',
    toState: 'Maharashtra',
    vehicleType: 'Truck 14ft',
    loadType: 'Pharma',
    tripDate: '2025-07-19',
    tripTime: '06:30',
    expectedFare: 22000,
    weightTons: 6,
    notes: 'Temperature-controlled cargo',
    status: 'open',
    isPremiumVendor: true,
    contactsCount: 4,
    contactedDrivers: [],
    createdAt: '2025-07-09T11:00:00Z',
  },
  {
    id: 'tr-v001-005',
    vendorId: 'v001',
    vendorName: 'Rajesh Patel',
    vendorPhone: '+91 98250 11234',
    fromCity: 'Ahmedabad',
    toCity: 'Hyderabad',
    fromState: 'Gujarat',
    toState: 'Telangana',
    vehicleType: 'Truck 32ft',
    loadType: 'Steel',
    tripDate: '2025-07-16',
    tripTime: '03:00',
    expectedFare: 68000,
    weightTons: 22,
    status: 'closed',
    isPremiumVendor: true,
    contactsCount: 12,
    contactedDrivers: [],
    closureType: 'outside_driver',
    closureNotes: 'Found driver through personal contact',
    createdAt: '2025-07-06T07:00:00Z',
  },
];

export const availableTripsForDriver: AppTrip[] = [
  {
    id: 'tr-open-001',
    vendorId: 'v001',
    vendorName: 'Rajesh Patel',
    vendorPhone: '+91 98250 11234',
    fromCity: 'Ahmedabad',
    toCity: 'Delhi',
    fromState: 'Gujarat',
    toState: 'Delhi',
    vehicleType: 'Truck 32ft',
    loadType: 'Auto Parts',
    tripDate: '2025-07-21',
    tripTime: '04:00',
    expectedFare: 55000,
    weightTons: 18,
    notes: 'Experienced driver required',
    status: 'open',
    isPremiumVendor: true,
    contactsCount: 3,
    contactedDrivers: [],
    createdAt: '2025-07-11T06:00:00Z',
  },
  {
    id: 'tr-open-002',
    vendorId: 'v002',
    vendorName: 'Suresh Shah',
    vendorPhone: '+91 99090 44567',
    fromCity: 'Surat',
    toCity: 'Mumbai',
    fromState: 'Gujarat',
    toState: 'Maharashtra',
    vehicleType: 'Mini Truck',
    loadType: 'Textile',
    tripDate: '2025-07-20',
    tripTime: '07:00',
    expectedFare: 12000,
    weightTons: 4,
    status: 'open',
    isPremiumVendor: false,
    contactsCount: 1,
    contactedDrivers: [],
    createdAt: '2025-07-12T09:00:00Z',
  },
  {
    id: 'tr-open-003',
    vendorId: 'v003',
    vendorName: 'Mohan Verma',
    vendorPhone: '+91 97140 33456',
    fromCity: 'Vadodara',
    toCity: 'Mumbai',
    fromState: 'Gujarat',
    toState: 'Maharashtra',
    vehicleType: 'Truck 14ft',
    loadType: 'General Cargo',
    tripDate: '2025-07-20',
    tripTime: '06:00',
    expectedFare: 18000,
    weightTons: 5,
    status: 'open',
    isPremiumVendor: false,
    contactsCount: 2,
    contactedDrivers: [],
    createdAt: '2025-07-10T08:00:00Z',
  },
  {
    id: 'tr-open-004',
    vendorId: 'v004',
    vendorName: 'Kirti Logistics',
    vendorPhone: '+91 96010 55678',
    fromCity: 'Rajkot',
    toCity: 'Ahmedabad',
    fromState: 'Gujarat',
    toState: 'Gujarat',
    vehicleType: 'Tempo',
    loadType: 'FMCG',
    tripDate: '2025-07-19',
    tripTime: '08:30',
    expectedFare: 6500,
    weightTons: 2,
    status: 'open',
    isPremiumVendor: true,
    contactsCount: 0,
    contactedDrivers: [],
    createdAt: '2025-07-13T07:30:00Z',
  },
  {
    id: 'tr-open-005',
    vendorId: 'v005',
    vendorName: 'Bharat Cargo',
    vendorPhone: '+91 87900 22345',
    fromCity: 'Ahmedabad',
    toCity: 'Jaipur',
    fromState: 'Gujarat',
    toState: 'Rajasthan',
    vehicleType: 'Truck 22ft',
    loadType: 'Ceramics',
    tripDate: '2025-07-23',
    tripTime: '05:00',
    expectedFare: 30000,
    weightTons: 11,
    status: 'open',
    isPremiumVendor: false,
    contactsCount: 4,
    contactedDrivers: [],
    createdAt: '2025-07-11T10:00:00Z',
  },
  {
    id: 'tr-open-006',
    vendorId: 'v001',
    vendorName: 'Rajesh Patel',
    vendorPhone: '+91 98250 11234',
    fromCity: 'Gandhinagar',
    toCity: 'Mumbai',
    fromState: 'Gujarat',
    toState: 'Maharashtra',
    vehicleType: 'Truck 14ft',
    loadType: 'Pharma',
    tripDate: '2025-07-19',
    tripTime: '06:30',
    expectedFare: 22000,
    weightTons: 6,
    notes: 'Temperature-controlled',
    status: 'open',
    isPremiumVendor: true,
    contactsCount: 4,
    contactedDrivers: [],
    createdAt: '2025-07-09T11:00:00Z',
  },
  {
    id: 'tr-open-007',
    vendorId: 'v006',
    vendorName: 'Navkar Transport',
    vendorPhone: '+91 93750 66789',
    fromCity: 'Mumbai',
    toCity: 'Ahmedabad',
    fromState: 'Maharashtra',
    toState: 'Gujarat',
    vehicleType: 'Truck 32ft',
    loadType: 'Steel',
    tripDate: '2025-07-24',
    tripTime: '03:00',
    expectedFare: 48000,
    weightTons: 20,
    status: 'open',
    isPremiumVendor: true,
    contactsCount: 6,
    contactedDrivers: [],
    createdAt: '2025-07-10T05:00:00Z',
  },
  {
    id: 'tr-open-008',
    vendorId: 'v007',
    vendorName: 'Kadam Travels',
    vendorPhone: '+91 77770 88901',
    fromCity: 'Pune',
    toCity: 'Surat',
    fromState: 'Maharashtra',
    toState: 'Gujarat',
    vehicleType: 'Mini Truck',
    loadType: 'Electronics',
    tripDate: '2025-07-22',
    tripTime: '09:00',
    expectedFare: 15000,
    weightTons: 3,
    status: 'open',
    isPremiumVendor: false,
    contactsCount: 2,
    contactedDrivers: [],
    createdAt: '2025-07-12T12:00:00Z',
  },
  {
    id: 'tr-open-009',
    vendorId: 'v002',
    vendorName: 'Suresh Shah',
    vendorPhone: '+91 99090 44567',
    fromCity: 'Surat',
    toCity: 'Jaipur',
    fromState: 'Gujarat',
    toState: 'Rajasthan',
    vehicleType: 'Truck 22ft',
    loadType: 'Marble',
    tripDate: '2025-07-26',
    tripTime: '04:30',
    expectedFare: 38000,
    weightTons: 14,
    status: 'open',
    isPremiumVendor: false,
    contactsCount: 0,
    contactedDrivers: [],
    createdAt: '2025-07-13T08:00:00Z',
  },
  {
    id: 'tr-open-010',
    vendorId: 'v004',
    vendorName: 'Kirti Logistics',
    vendorPhone: '+91 96010 55678',
    fromCity: 'Ahmedabad',
    toCity: 'Hyderabad',
    fromState: 'Gujarat',
    toState: 'Telangana',
    vehicleType: 'Truck 32ft',
    loadType: 'Chemicals',
    tripDate: '2025-07-27',
    tripTime: '02:00',
    expectedFare: 72000,
    weightTons: 24,
    notes: 'Hazmat licensed driver needed',
    status: 'open',
    isPremiumVendor: true,
    contactsCount: 1,
    contactedDrivers: [],
    createdAt: '2025-07-12T06:00:00Z',
  },
  {
    id: 'tr-open-011',
    vendorId: 'v005',
    vendorName: 'Bharat Cargo',
    vendorPhone: '+91 87900 22345',
    fromCity: 'Vadodara',
    toCity: 'Rajkot',
    fromState: 'Gujarat',
    toState: 'Gujarat',
    vehicleType: 'Tempo',
    loadType: 'Agriculture',
    tripDate: '2025-07-20',
    tripTime: '07:30',
    expectedFare: 8000,
    weightTons: 2.5,
    status: 'open',
    isPremiumVendor: false,
    contactsCount: 3,
    contactedDrivers: [],
    createdAt: '2025-07-11T14:00:00Z',
  },
];

export const demoNotifications: AppNotification[] = [
  {
    id: 'notif-001',
    type: 'driver_contacted',
    title: 'Driver Contacted Your Trip',
    body: 'Harshad Bhatt (Sedan) contacted you for Ahmedabad → Delhi trip',
    read: false,
    createdAt: '2025-07-13T10:30:00Z',
    tripId: 'tr-v001-001',
  },
  {
    id: 'notif-002',
    type: 'premium_expiring',
    title: 'Premium Expiring Soon',
    body: 'Your Premium membership expires on Aug 15, 2025. Renew to keep benefits.',
    read: false,
    createdAt: '2025-07-13T09:00:00Z',
  },
  {
    id: 'notif-003',
    type: 'trip_closed',
    title: 'Trip Closed Successfully',
    body: 'Vadodara → Surat trip has been closed. Driver assigned.',
    read: true,
    createdAt: '2025-07-12T16:00:00Z',
    tripId: 'tr-v003-002',
  },
];
