import type { AppUser, AppTrip, AppNotification } from './app-types';

export const demoUsers: Record<string, AppUser> = {
  vendorFree: {
    id: 'v003',
    name: 'Mohan Verma',
    phone: '+91 97140 33456',
    email: 'mohan@vermatransport.in',
    role: 'vendor',
    status: 'active',
    isPremium: false,
    city: 'Vadodara',
    companyName: 'Verma Travels',
  },
  vendorPremium: {
    id: 'v001',
    name: 'Rajesh Patel',
    phone: '+91 98250 11234',
    email: 'rajesh@pateltravels.com',
    role: 'vendor',
    status: 'active',
    isPremium: true,
    premiumExpiry: '2026-08-15',
    city: 'Ahmedabad',
    companyName: 'Patel Travels',
  },
  driverFree: {
    id: 'd003',
    name: 'Ramesh Yadav',
    phone: '+91 88660 87654',
    email: 'ramesh.yadav@gmail.com',
    role: 'driver',
    status: 'active',
    isPremium: false,
    city: 'Surat',
    vehicleType: 'Hatchback (Swift)',
  },
  driverPremium: {
    id: 'd001',
    name: 'Harshad Bhatt',
    phone: '+91 98250 65432',
    email: 'harshad@gmail.com',
    role: 'driver',
    status: 'active',
    isPremium: true,
    premiumExpiry: '2026-08-20',
    city: 'Ahmedabad',
    vehicleType: 'Sedan (Toyota Etios)',
  },
};

export const vendorFreeTrips: AppTrip[] = [
  {
    id: 'tr-v003-001',
    vendorId: 'v003',
    vendorName: 'Mohan Verma',
    vendorPhone: '+91 97140 33456',
    fromCity: 'Vadodara',
    toCity: 'Mumbai',
    fromState: 'Gujarat',
    toState: 'Maharashtra',
    vehicleType: 'SUV',
    loadType: 'Corporate Transfer',
    tripDate: '2026-07-20',
    tripTime: '06:00',
    expectedFare: 4500,
    notes: 'Morning departure preferred',
    status: 'open',
    isPremiumVendor: false,
    contactsCount: 2,
    contactedDrivers: [],
    createdAt: '2026-07-10T08:00:00Z',
  },
  {
    id: 'tr-v003-002',
    vendorId: 'v003',
    vendorName: 'Mohan Verma',
    vendorPhone: '+91 97140 33456',
    fromCity: 'Vadodara',
    toCity: 'Surat',
    fromState: 'Gujarat',
    toState: 'Gujarat',
    vehicleType: 'Sedan',
    loadType: 'City to City',
    tripDate: '2026-07-18',
    tripTime: '09:00',
    expectedFare: 1800,
    status: 'closed',
    isPremiumVendor: false,
    contactsCount: 5,
    contactedDrivers: [],
    closureType: 'app_driver',
    closedDriverId: 'd002',
    createdAt: '2026-07-08T10:00:00Z',
  },
  {
    id: 'tr-v003-003',
    vendorId: 'v003',
    vendorName: 'Mohan Verma',
    vendorPhone: '+91 97140 33456',
    fromCity: 'Vadodara',
    toCity: 'Rajkot',
    fromState: 'Gujarat',
    toState: 'Gujarat',
    vehicleType: 'Tempo Travel',
    loadType: 'Group Outstation',
    tripDate: '2026-07-25',
    tripTime: '08:00',
    expectedFare: 6500,
    notes: '8 passengers, AC required',
    status: 'open',
    isPremiumVendor: false,
    contactsCount: 1,
    contactedDrivers: [],
    createdAt: '2026-07-12T09:30:00Z',
  },
  {
    id: 'tr-v003-004',
    vendorId: 'v003',
    vendorName: 'Mohan Verma',
    vendorPhone: '+91 97140 33456',
    fromCity: 'Anand',
    toCity: 'Pune',
    fromState: 'Gujarat',
    toState: 'Maharashtra',
    vehicleType: 'Innova Crysta',
    loadType: 'Outstation',
    tripDate: '2026-07-22',
    tripTime: '05:30',
    expectedFare: 8500,
    status: 'open',
    isPremiumVendor: false,
    contactsCount: 0,
    contactedDrivers: [],
    createdAt: '2026-07-13T07:00:00Z',
  },
];

export const vendorPremiumTrips: AppTrip[] = [
  {
    id: 'tr-v001-001',
    vendorId: 'v001',
    vendorName: 'Rajesh Patel',
    vendorPhone: '+91 98250 11234',
    fromCity: 'Ahmedabad',
    toCity: 'Delhi',
    fromState: 'Gujarat',
    toState: 'Delhi',
    vehicleType: 'Innova Crysta',
    loadType: 'Corporate Transfer',
    tripDate: '2026-07-21',
    tripTime: '04:00',
    expectedFare: 18000,
    notes: 'VIP client, professional driver required',
    status: 'open',
    isPremiumVendor: true,
    contactsCount: 3,
    contactedDrivers: [
      { driverId: 'd001', driverName: 'Harshad Bhatt', driverPhone: '+91 98250 65432', vehicleType: 'Sedan', city: 'Ahmedabad', isPremium: true, contactMethod: 'call', contactedAt: '2026-07-12T08:30:00Z' },
      { driverId: 'd004', driverName: 'Vinay Desai', driverPhone: '+91 91540 22345', vehicleType: 'SUV', city: 'Gandhinagar', isPremium: false, contactMethod: 'whatsapp', contactedAt: '2026-07-12T11:00:00Z' },
      { driverId: 'd005', driverName: 'Arjun Singh', driverPhone: '+91 87650 99123', vehicleType: 'Innova Crysta', city: 'Ahmedabad', isPremium: true, contactMethod: 'call', contactedAt: '2026-07-13T07:15:00Z' },
    ],
    createdAt: '2026-07-11T06:00:00Z',
  },
  {
    id: 'tr-v001-002',
    vendorId: 'v001',
    vendorName: 'Rajesh Patel',
    vendorPhone: '+91 98250 11234',
    fromCity: 'Ahmedabad',
    toCity: 'Surat',
    fromState: 'Gujarat',
    toState: 'Gujarat',
    vehicleType: 'Sedan',
    loadType: 'City to City',
    tripDate: '2026-07-17',
    tripTime: '07:00',
    expectedFare: 2200,
    status: 'closed',
    isPremiumVendor: true,
    contactsCount: 8,
    contactedDrivers: [],
    closureType: 'app_driver',
    closedDriverId: 'd003',
    createdAt: '2026-07-07T08:00:00Z',
  },
  {
    id: 'tr-v001-003',
    vendorId: 'v001',
    vendorName: 'Rajesh Patel',
    vendorPhone: '+91 98250 11234',
    fromCity: 'Ahmedabad',
    toCity: 'Jaipur',
    fromState: 'Gujarat',
    toState: 'Rajasthan',
    vehicleType: 'Luxury Car',
    loadType: 'Wedding / Event',
    tripDate: '2026-07-28',
    tripTime: '05:00',
    expectedFare: 22000,
    notes: 'Decorated car needed for wedding party',
    status: 'open',
    isPremiumVendor: true,
    contactsCount: 1,
    contactedDrivers: [],
    createdAt: '2026-07-13T10:00:00Z',
  },
  {
    id: 'tr-v001-004',
    vendorId: 'v001',
    vendorName: 'Rajesh Patel',
    vendorPhone: '+91 98250 11234',
    fromCity: 'Gandhinagar',
    toCity: 'Mumbai',
    fromState: 'Gujarat',
    toState: 'Maharashtra',
    vehicleType: 'SUV',
    loadType: 'Airport Transfer',
    tripDate: '2026-07-19',
    tripTime: '06:30',
    expectedFare: 7500,
    notes: 'Flight at 10:00 AM, early pickup needed',
    status: 'open',
    isPremiumVendor: true,
    contactsCount: 4,
    contactedDrivers: [],
    createdAt: '2026-07-09T11:00:00Z',
  },
  {
    id: 'tr-v001-005',
    vendorId: 'v001',
    vendorName: 'Rajesh Patel',
    vendorPhone: '+91 98250 11234',
    fromCity: 'Ahmedabad',
    toCity: 'Hyderabad',
    fromState: 'Gujarat',
    toState: 'Telangana',
    vehicleType: 'Innova',
    loadType: 'Outstation',
    tripDate: '2026-07-16',
    tripTime: '03:00',
    expectedFare: 15000,
    status: 'closed',
    isPremiumVendor: true,
    contactsCount: 12,
    contactedDrivers: [],
    closureType: 'outside_driver',
    closureNotes: 'Found driver through personal contact',
    createdAt: '2026-07-06T07:00:00Z',
  },
];

export const availableTripsForDriver: AppTrip[] = [
  {
    id: 'tr-open-001',
    vendorId: 'v001',
    vendorName: 'Rajesh Patel',
    vendorPhone: '+91 98250 11234',
    fromCity: 'Ahmedabad',
    toCity: 'Delhi',
    fromState: 'Gujarat',
    toState: 'Delhi',
    vehicleType: 'Innova Crysta',
    loadType: 'Corporate Transfer',
    tripDate: '2026-07-21',
    tripTime: '04:00',
    expectedFare: 18000,
    notes: 'VIP client, professional driver required',
    status: 'open',
    isPremiumVendor: true,
    contactsCount: 3,
    contactedDrivers: [],
    createdAt: '2026-07-11T06:00:00Z',
  },
  {
    id: 'tr-open-002',
    vendorId: 'v002',
    vendorName: 'Suresh Shah',
    vendorPhone: '+91 99090 44567',
    fromCity: 'Surat',
    toCity: 'Mumbai',
    fromState: 'Gujarat',
    toState: 'Maharashtra',
    vehicleType: 'Sedan',
    loadType: 'City to City',
    tripDate: '2026-07-20',
    tripTime: '07:00',
    expectedFare: 3200,
    status: 'open',
    isPremiumVendor: false,
    contactsCount: 1,
    contactedDrivers: [],
    createdAt: '2026-07-12T09:00:00Z',
  },
  {
    id: 'tr-open-003',
    vendorId: 'v003',
    vendorName: 'Mohan Verma',
    vendorPhone: '+91 97140 33456',
    fromCity: 'Vadodara',
    toCity: 'Mumbai',
    fromState: 'Gujarat',
    toState: 'Maharashtra',
    vehicleType: 'SUV',
    loadType: 'Airport Transfer',
    tripDate: '2026-07-20',
    tripTime: '06:00',
    expectedFare: 5500,
    status: 'open',
    isPremiumVendor: false,
    contactsCount: 2,
    contactedDrivers: [],
    createdAt: '2026-07-10T08:00:00Z',
  },
  {
    id: 'tr-open-004',
    vendorId: 'v004',
    vendorName: 'Kirti Travels',
    vendorPhone: '+91 96010 55678',
    fromCity: 'Rajkot',
    toCity: 'Ahmedabad',
    fromState: 'Gujarat',
    toState: 'Gujarat',
    vehicleType: 'Hatchback',
    loadType: 'City to City',
    tripDate: '2026-07-19',
    tripTime: '08:30',
    expectedFare: 1800,
    status: 'open',
    isPremiumVendor: true,
    contactsCount: 0,
    contactedDrivers: [],
    createdAt: '2026-07-13T07:30:00Z',
  },
  {
    id: 'tr-open-005',
    vendorId: 'v005',
    vendorName: 'Bharat Tours',
    vendorPhone: '+91 87900 22345',
    fromCity: 'Ahmedabad',
    toCity: 'Jaipur',
    fromState: 'Gujarat',
    toState: 'Rajasthan',
    vehicleType: 'Tempo Travel',
    loadType: 'Group Outstation',
    tripDate: '2026-07-23',
    tripTime: '05:00',
    expectedFare: 12000,
    notes: '12 passengers, overnight trip',
    status: 'open',
    isPremiumVendor: false,
    contactsCount: 4,
    contactedDrivers: [],
    createdAt: '2026-07-11T10:00:00Z',
  },
  {
    id: 'tr-open-006',
    vendorId: 'v001',
    vendorName: 'Rajesh Patel',
    vendorPhone: '+91 98250 11234',
    fromCity: 'Gandhinagar',
    toCity: 'Mumbai',
    fromState: 'Gujarat',
    toState: 'Maharashtra',
    vehicleType: 'SUV',
    loadType: 'Airport Transfer',
    tripDate: '2026-07-19',
    tripTime: '06:30',
    expectedFare: 7500,
    notes: 'Flight at 10:00 AM',
    status: 'open',
    isPremiumVendor: true,
    contactsCount: 4,
    contactedDrivers: [],
    createdAt: '2026-07-09T11:00:00Z',
  },
  {
    id: 'tr-open-007',
    vendorId: 'v006',
    vendorName: 'Navkar Travels',
    vendorPhone: '+91 93750 66789',
    fromCity: 'Mumbai',
    toCity: 'Ahmedabad',
    fromState: 'Maharashtra',
    toState: 'Gujarat',
    vehicleType: 'Innova Crysta',
    loadType: 'Outstation',
    tripDate: '2026-07-24',
    tripTime: '08:00',
    expectedFare: 12000,
    status: 'open',
    isPremiumVendor: true,
    contactsCount: 6,
    contactedDrivers: [],
    createdAt: '2026-07-10T05:00:00Z',
  },
  {
    id: 'tr-open-008',
    vendorId: 'v007',
    vendorName: 'Kadam Travels',
    vendorPhone: '+91 77770 88901',
    fromCity: 'Pune',
    toCity: 'Surat',
    fromState: 'Maharashtra',
    toState: 'Gujarat',
    vehicleType: 'Mini Bus',
    loadType: 'Group Transfer',
    tripDate: '2026-07-22',
    tripTime: '09:00',
    expectedFare: 9000,
    notes: '20 pax, AC bus preferred',
    status: 'open',
    isPremiumVendor: false,
    contactsCount: 2,
    contactedDrivers: [],
    createdAt: '2026-07-12T12:00:00Z',
  },
  {
    id: 'tr-open-009',
    vendorId: 'v002',
    vendorName: 'Suresh Shah',
    vendorPhone: '+91 99090 44567',
    fromCity: 'Surat',
    toCity: 'Jaipur',
    fromState: 'Gujarat',
    toState: 'Rajasthan',
    vehicleType: 'Bus',
    loadType: 'Pilgrimage Tour',
    tripDate: '2026-07-26',
    tripTime: '04:30',
    expectedFare: 35000,
    notes: '40 passengers, Pushkar yatra',
    status: 'open',
    isPremiumVendor: false,
    contactsCount: 0,
    contactedDrivers: [],
    createdAt: '2026-07-13T08:00:00Z',
  },
  {
    id: 'tr-open-010',
    vendorId: 'v004',
    vendorName: 'Kirti Travels',
    vendorPhone: '+91 96010 55678',
    fromCity: 'Ahmedabad',
    toCity: 'Hyderabad',
    fromState: 'Gujarat',
    toState: 'Telangana',
    vehicleType: 'Luxury Car',
    loadType: 'Corporate Transfer',
    tripDate: '2026-07-27',
    tripTime: '06:00',
    expectedFare: 28000,
    notes: 'Senior executive, chauffeur service required',
    status: 'open',
    isPremiumVendor: true,
    contactsCount: 1,
    contactedDrivers: [],
    createdAt: '2026-07-12T06:00:00Z',
  },
  {
    id: 'tr-open-011',
    vendorId: 'v005',
    vendorName: 'Bharat Tours',
    vendorPhone: '+91 87900 22345',
    fromCity: 'Vadodara',
    toCity: 'Rajkot',
    fromState: 'Gujarat',
    toState: 'Gujarat',
    vehicleType: 'Innova',
    loadType: 'Outstation',
    tripDate: '2026-07-20',
    tripTime: '07:30',
    expectedFare: 4200,
    status: 'open',
    isPremiumVendor: false,
    contactsCount: 3,
    contactedDrivers: [],
    createdAt: '2026-07-11T14:00:00Z',
  },
];

export const demoNotifications: AppNotification[] = [
  {
    id: 'notif-001',
    type: 'driver_contacted',
    title: 'Driver Contacted Your Trip',
    body: 'Harshad Bhatt (Sedan) contacted you for Ahmedabad → Delhi trip',
    read: false,
    createdAt: '2026-07-13T10:30:00Z',
    tripId: 'tr-v001-001',
  },
  {
    id: 'notif-002',
    type: 'premium_expiring',
    title: 'Premium Expiring Soon',
    body: 'Your Premium membership expires on Aug 15, 2026. Renew to keep benefits.',
    read: false,
    createdAt: '2026-07-13T09:00:00Z',
  },
  {
    id: 'notif-003',
    type: 'trip_closed',
    title: 'Trip Closed Successfully',
    body: 'Vadodara → Surat trip has been closed. Driver assigned.',
    read: true,
    createdAt: '2026-07-12T16:00:00Z',
    tripId: 'tr-v003-002',
  },
];
